// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type WeddingDocumentDataSlicesSlice =
  | VisionSlice
  | UbicationSlice
  | TimerSlice
  | SliderSlice
  | ScheduleSlice
  | PhrasesSlice
  | OurMomentsSlice
  | MainSlice
  | LodgingSlice
  | GifsSlice
  | ConfirmationSlice;

/**
 * Content for Wedding documents
 */
interface WeddingDocumentData {
  /**
   * Slice Zone field in *Wedding*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: wedding.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<WeddingDocumentDataSlicesSlice> /**
   * Meta Title field in *Wedding*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: wedding.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Wedding*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: wedding.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Wedding*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: wedding.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Wedding document from Prismic
 *
 * - **API ID**: `wedding`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WeddingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<WeddingDocumentData>,
    "wedding",
    Lang
  >;

export type AllDocumentTypes = WeddingDocument;

/**
 * Primary content in *Confirmation → Default → Primary*
 */
export interface ConfirmationSliceDefaultPrimary {
  /**
   * Title field in *Confirmation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: confirmation.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Confirmation → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: confirmation.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Default variation for Confirmation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ConfirmationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ConfirmationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Confirmation*
 */
type ConfirmationSliceVariation = ConfirmationSliceDefault;

/**
 * Confirmation Shared Slice
 *
 * - **API ID**: `confirmation`
 * - **Description**: Confirmation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ConfirmationSlice = prismic.SharedSlice<
  "confirmation",
  ConfirmationSliceVariation
>;

/**
 * Primary content in *Gifts → Default → Primary*
 */
export interface GifsSliceDefaultPrimary {
  /**
   * Title field in *Gifts → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gifs.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * ImageDecoration field in *Gifts → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gifs.default.primary.imagedecoration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagedecoration: prismic.ImageField<never>;

  /**
   * LinkButton field in *Gifts → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: gifs.default.primary.linkbutton
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkbutton: prismic.LinkField;

  /**
   * LabelButton field in *Gifts → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gifs.default.primary.labelbutton
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelbutton: prismic.KeyTextField;

  /**
   * ImageDecoration2 field in *Gifts → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gifs.default.primary.imagedecoration2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagedecoration2: prismic.ImageField<never>;
}

/**
 * Default variation for Gifts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GifsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GifsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Gifts*
 */
type GifsSliceVariation = GifsSliceDefault;

/**
 * Gifts Shared Slice
 *
 * - **API ID**: `gifs`
 * - **Description**: Gifs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GifsSlice = prismic.SharedSlice<"gifs", GifsSliceVariation>;

/**
 * Primary content in *Lodging → Default → Primary*
 */
export interface LodgingSliceDefaultPrimary {
  /**
   * Title field in *Lodging → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lodging.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * ImageDecoration field in *Lodging → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: lodging.default.primary.imagedecoration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagedecoration: prismic.ImageField<never>;

  /**
   * Direction field in *Lodging → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lodging.default.primary.direction
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  direction: prismic.KeyTextField;

  /**
   * DirectionValue field in *Lodging → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lodging.default.primary.directionvalue
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  directionvalue: prismic.KeyTextField;

  /**
   * Count field in *Lodging → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lodging.default.primary.count
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  count: prismic.KeyTextField;

  /**
   * CountValue field in *Lodging → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lodging.default.primary.countvalue
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  countvalue: prismic.KeyTextField;

  /**
   * LinkButton field in *Lodging → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: lodging.default.primary.linkbutton
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkbutton: prismic.LinkField;

  /**
   * LabelButton field in *Lodging → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lodging.default.primary.labelbutton
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelbutton: prismic.KeyTextField;
}

/**
 * Default variation for Lodging Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LodgingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LodgingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Lodging*
 */
type LodgingSliceVariation = LodgingSliceDefault;

/**
 * Lodging Shared Slice
 *
 * - **API ID**: `lodging`
 * - **Description**: Lodging
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LodgingSlice = prismic.SharedSlice<
  "lodging",
  LodgingSliceVariation
>;

/**
 * Item in *Main → Default → Primary → GroupMain*
 */
export interface MainSliceDefaultPrimaryGroupmainItem {
  /**
   * Image field in *Main → Default → Primary → GroupMain*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main.default.primary.groupmain[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Main → Default → Primary*
 */
export interface MainSliceDefaultPrimary {
  /**
   * Tittle field in *Main → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main.default.primary.tittle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tittle: prismic.RichTextField;

  /**
   * Subtittle field in *Main → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main.default.primary.subtittle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtittle: prismic.KeyTextField;

  /**
   * Description field in *Main → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * GroupMain field in *Main → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: main.default.primary.groupmain[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupmain: prismic.GroupField<Simplify<MainSliceDefaultPrimaryGroupmainItem>>;
}

/**
 * Default variation for Main Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MainSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Main*
 */
type MainSliceVariation = MainSliceDefault;

/**
 * Main Shared Slice
 *
 * - **API ID**: `main`
 * - **Description**: Main
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainSlice = prismic.SharedSlice<"main", MainSliceVariation>;

/**
 * Item in *OurMoments → Default → Primary → GroupMoments*
 */
export interface OurMomentsSliceDefaultPrimaryGroupmomentsItem {
  /**
   * Image field in *OurMoments → Default → Primary → GroupMoments*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_moments.default.primary.groupmoments[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *OurMoments → Default → Primary*
 */
export interface OurMomentsSliceDefaultPrimary {
  /**
   * Title field in *OurMoments → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_moments.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *OurMoments → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_moments.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * GroupMoments field in *OurMoments → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: our_moments.default.primary.groupmoments[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupmoments: prismic.GroupField<
    Simplify<OurMomentsSliceDefaultPrimaryGroupmomentsItem>
  >;
}

/**
 * Default variation for OurMoments Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurMomentsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurMomentsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurMoments*
 */
type OurMomentsSliceVariation = OurMomentsSliceDefault;

/**
 * OurMoments Shared Slice
 *
 * - **API ID**: `our_moments`
 * - **Description**: OurMoments
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurMomentsSlice = prismic.SharedSlice<
  "our_moments",
  OurMomentsSliceVariation
>;

/**
 * Primary content in *Phrases → Default → Primary*
 */
export interface PhrasesSliceDefaultPrimary {
  /**
   * Tittle One field in *Phrases → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: phrases.default.primary.tittle_one
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tittle_one: prismic.RichTextField;

  /**
   * Subtittle One field in *Phrases → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: phrases.default.primary.subtittle_one
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtittle_one: prismic.KeyTextField;

  /**
   * Image One field in *Phrases → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: phrases.default.primary.image_one
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_one: prismic.ImageField<never>;

  /**
   * Tittle Two field in *Phrases → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: phrases.default.primary.tittle_two
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tittle_two: prismic.RichTextField;

  /**
   * Subtittle Two field in *Phrases → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: phrases.default.primary.subtittle_two
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtittle_two: prismic.KeyTextField;

  /**
   * Image Two field in *Phrases → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: phrases.default.primary.image_two
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_two: prismic.ImageField<never>;
}

/**
 * Default variation for Phrases Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PhrasesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PhrasesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Phrases*
 */
type PhrasesSliceVariation = PhrasesSliceDefault;

/**
 * Phrases Shared Slice
 *
 * - **API ID**: `phrases`
 * - **Description**: Phrases
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PhrasesSlice = prismic.SharedSlice<
  "phrases",
  PhrasesSliceVariation
>;

/**
 * Item in *Schedule → Default → Primary → GroupSchedule*
 */
export interface ScheduleSliceDefaultPrimaryGroupscheduleItem {
  /**
   * Text field in *Schedule → Default → Primary → GroupSchedule*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule.default.primary.groupschedule[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Image field in *Schedule → Default → Primary → GroupSchedule*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule.default.primary.groupschedule[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Time field in *Schedule → Default → Primary → GroupSchedule*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule.default.primary.groupschedule[].time
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  time: prismic.KeyTextField;
}

/**
 * Primary content in *Schedule → Default → Primary*
 */
export interface ScheduleSliceDefaultPrimary {
  /**
   * Title field in *Schedule → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * GroupSchedule field in *Schedule → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule.default.primary.groupschedule[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupschedule: prismic.GroupField<
    Simplify<ScheduleSliceDefaultPrimaryGroupscheduleItem>
  >;
}

/**
 * Default variation for Schedule Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScheduleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScheduleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Schedule*
 */
type ScheduleSliceVariation = ScheduleSliceDefault;

/**
 * Schedule Shared Slice
 *
 * - **API ID**: `schedule`
 * - **Description**: Schedule
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScheduleSlice = prismic.SharedSlice<
  "schedule",
  ScheduleSliceVariation
>;

/**
 * Primary content in *Slider → Default → Primary*
 */
export interface SliderSliceDefaultPrimary {
  /**
   * Image One field in *Slider → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.image_one
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_one: prismic.ImageField<never>;

  /**
   * Image Two field in *Slider → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.image_two
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_two: prismic.ImageField<never>;

  /**
   * Image Three field in *Slider → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.image_three
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_three: prismic.ImageField<never>;

  /**
   * Image Four field in *Slider → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.image_four
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_four: prismic.ImageField<never>;

  /**
   * Image Five field in *Slider → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.image_five
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_five: prismic.ImageField<never>;

  /**
   * Image Six field in *Slider → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.image_six
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_six: prismic.ImageField<never>;
}

/**
 * Default variation for Slider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Slider*
 */
type SliderSliceVariation = SliderSliceDefault;

/**
 * Slider Shared Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Slider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSlice = prismic.SharedSlice<"slider", SliderSliceVariation>;

/**
 * Primary content in *Timer → Default → Primary*
 */
export interface TimerSliceDefaultPrimary {
  /**
   * Tittle field in *Timer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timer.default.primary.tittle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tittle: prismic.RichTextField;

  /**
   * Subtittle field in *Timer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timer.default.primary.subtittle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtittle: prismic.KeyTextField;

  /**
   * Image Decoration field in *Timer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: timer.default.primary.image_decoration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_decoration: prismic.ImageField<never>;
}

/**
 * Default variation for Timer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Timer*
 */
type TimerSliceVariation = TimerSliceDefault;

/**
 * Timer Shared Slice
 *
 * - **API ID**: `timer`
 * - **Description**: Timer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimerSlice = prismic.SharedSlice<"timer", TimerSliceVariation>;

/**
 * Item in *Ubication → Default → Primary → GroupUbication*
 */
export interface UbicationSliceDefaultPrimaryGroupubicationItem {
  /**
   * Label field in *Ubication → Default → Primary → GroupUbication*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.groupubication[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *Ubication → Default → Primary*
 */
export interface UbicationSliceDefaultPrimary {
  /**
   * Tittle field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.tittle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tittle: prismic.RichTextField;

  /**
   * Subtittle field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.subtittle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtittle: prismic.KeyTextField;

  /**
   * GroupUbication field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.groupubication[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupubication: prismic.GroupField<
    Simplify<UbicationSliceDefaultPrimaryGroupubicationItem>
  >;

  /**
   * Image Decoration field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.image_decoration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_decoration: prismic.ImageField<never>;

  /**
   * LinkButton field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.linkbutton
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkbutton: prismic.LinkField;

  /**
   * Button field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button: prismic.KeyTextField;
}

/**
 * Default variation for Ubication Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UbicationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<UbicationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Ubication*
 */
type UbicationSliceVariation = UbicationSliceDefault;

/**
 * Ubication Shared Slice
 *
 * - **API ID**: `ubication`
 * - **Description**: Ubication
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UbicationSlice = prismic.SharedSlice<
  "ubication",
  UbicationSliceVariation
>;

/**
 * Primary content in *Vision → Default → Primary*
 */
export interface VisionSliceDefaultPrimary {
  /**
   * ImageDecoration field in *Vision → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: vision.default.primary.imagedecoration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagedecoration: prismic.ImageField<never>;

  /**
   * Phrase1 field in *Vision → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision.default.primary.phrase1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phrase1: prismic.KeyTextField;

  /**
   * Prhase2 field in *Vision → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision.default.primary.prhase2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  prhase2: prismic.KeyTextField;
}

/**
 * Default variation for Vision Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VisionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VisionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Vision*
 */
type VisionSliceVariation = VisionSliceDefault;

/**
 * Vision Shared Slice
 *
 * - **API ID**: `vision`
 * - **Description**: Vision
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VisionSlice = prismic.SharedSlice<"vision", VisionSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      WeddingDocument,
      WeddingDocumentData,
      WeddingDocumentDataSlicesSlice,
      AllDocumentTypes,
      ConfirmationSlice,
      ConfirmationSliceDefaultPrimary,
      ConfirmationSliceVariation,
      ConfirmationSliceDefault,
      GifsSlice,
      GifsSliceDefaultPrimary,
      GifsSliceVariation,
      GifsSliceDefault,
      LodgingSlice,
      LodgingSliceDefaultPrimary,
      LodgingSliceVariation,
      LodgingSliceDefault,
      MainSlice,
      MainSliceDefaultPrimaryGroupmainItem,
      MainSliceDefaultPrimary,
      MainSliceVariation,
      MainSliceDefault,
      OurMomentsSlice,
      OurMomentsSliceDefaultPrimaryGroupmomentsItem,
      OurMomentsSliceDefaultPrimary,
      OurMomentsSliceVariation,
      OurMomentsSliceDefault,
      PhrasesSlice,
      PhrasesSliceDefaultPrimary,
      PhrasesSliceVariation,
      PhrasesSliceDefault,
      ScheduleSlice,
      ScheduleSliceDefaultPrimaryGroupscheduleItem,
      ScheduleSliceDefaultPrimary,
      ScheduleSliceVariation,
      ScheduleSliceDefault,
      SliderSlice,
      SliderSliceDefaultPrimary,
      SliderSliceVariation,
      SliderSliceDefault,
      TimerSlice,
      TimerSliceDefaultPrimary,
      TimerSliceVariation,
      TimerSliceDefault,
      UbicationSlice,
      UbicationSliceDefaultPrimaryGroupubicationItem,
      UbicationSliceDefaultPrimary,
      UbicationSliceVariation,
      UbicationSliceDefault,
      VisionSlice,
      VisionSliceDefaultPrimary,
      VisionSliceVariation,
      VisionSliceDefault,
    };
  }
}
