// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  confirmation: defineAsyncComponent(() => import("./Confirmation/index.vue")),
  gifs: defineAsyncComponent(() => import("./Gifts/index.vue")),
  lodging: defineAsyncComponent(() => import("./Lodging/index.vue")),
  main: defineAsyncComponent(() => import("./Main/index.vue")),
  our_moments: defineAsyncComponent(() => import("./OurMoments/index.vue")),
  phrases: defineAsyncComponent(() => import("./Phrases/index.vue")),
  schedule: defineAsyncComponent(() => import("./Schedule/index.vue")),
  slider: defineAsyncComponent(() => import("./Slider/index.vue")),
  timer: defineAsyncComponent(() => import("./Timer/index.vue")),
  ubication: defineAsyncComponent(() => import("./Ubication/index.vue")),
  vision: defineAsyncComponent(() => import("./Vision/index.vue")),
});
